services:
  # Go 轉碼服務
  converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-demo-converter
    restart: unless-stopped
    volumes:
      - ffmpeg_temp:/tmp/transcoding
    networks:
      - stream-demo-network
    environment:
      # 資料庫配置
      - DATABASE_URL=host=postgresql user=stream_user password=stream_password dbname=stream_demo port=5432 sslmode=disable
      # MinIO 配置
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=stream-demo-videos
      - MINIO_PROCESSED_BUCKET=stream-demo-processed
      # CDN 配置
      - CDN_BASE_URL=http://localhost:9000/stream-demo-processed
      # 工作協程配置
      - WORKER_COUNT=3
    healthcheck:
      test: ["CMD", "converter", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3

# 資料卷定義
volumes:
  ffmpeg_temp:
    driver: local

# 網路定義
networks:
  stream-demo-network:
    external: true 